replicas: 1

minimumMasterNodes: 1

esJavaOpts: "-Xms512m -Xmx512m"

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

roles:
  - master
  - ingest
  - data

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
